---
# server port config
server:
  port: 8080

# db connection info & fileupload config
spring:
  config:
    activate:
      on-profile: 
        - local
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##BUL_HR
    password: 1234

# jap config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true

jwt:
  secret: YcDq0URXmDIeeKjYz1afWM8ReWaHzDCc5d7ccEQCXYqUlLQKSq77px/n2znavLLNNu3P+GbPzpnKMqOC/I38jQ==


# Logging Level
# Logging Level
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type: trace

# 파일
image:
  add-resource-locations: classpath:/static/fileimgs/
  add-resource-handler: /fileimgs/**
#  add-resource-locations: classpath:/static/fileimgs/
#  add-resource-handler: /fileimgs/**
#
  image-dir: src/main/resources/static/fileimgs
  image-url: http://localhost:8080/fileimgs
