# server port config
server:
  port: 8080

# db connection info & fileupload config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:xe
    username: C##BUL_HR
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/

# jap config
jpa:
  generate-ddl: false
  show-sql: true
  database: oracle
  properties:
    hibernate:
      '[format_sql]': true

jwt:
  secret: YcDq0URXmDIeeKjYz1afWM8ReWaHzDCc5d7ccEQCXYqUlLQKSq77px/n2znavLLNNu3P+GbPzpnK MqOC/I38jQ==


# Logging Level
logging:
  level:
    root: info

image:
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**

  image-dir: src/main/resource/static/productimgs
  image-url: http://localhost:8080/productimgs/
