# server port config
server:
  port: 8080

# db connection info & fileupload config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:xe
    username: C##BUBBLE_BUBBLE
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/
  output:
        ansi:
            enabled: always
# jap config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        '[format_sql]': true
      

jwt:
  secret: YcDq0URXmDIeeKjYz1afWM8ReWaHzDCc5d7ccEQCXYqUlLQKSq77px/n2znavLLNNu3P+GbPzpnKMqOC/I38jQ==


# Logging Level
logging:
  level:
    root: info

# 파일
image:
  add-resource-locations: classpath:/static/fileimgs/
  add-resource-handler: /fileimgs/**

  image-dir: src/main/resources/static/fileimgs
  image-url: http://localhost:8080/fileimgs